-- 建立数据库
CREATE DATABASE IF NOT EXISTS s48_shop;

-- 选择数据库
USE s48_shop;

-- 用户表
CREATE TABLE IF NOT EXISTS `s48_user`(
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL UNIQUE KEY,
  `password` CHAR(32) NOT NULL,
  `role` TINYINT NOT NULL DEFAULT 0, -- 0普通用户 1管理员 2超级管理员
  `lock` TINYINT NOT NULL DEFAULT 0  -- 0开启 1关闭
)ENGINE=MYISAM DEFAULT CHARSET=utf8;

-- 添加超级管理员
INSERT INTO s48_user(id,name,password,role,`lock`) VALUES(NULL,'admin',md5('admin'),2,0);

-- 分类表
CREATE TABLE IF NOT EXISTS `s48_category`(
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `pid` TINYINT UNSIGNED NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `display` TINYINT UNSIGNED NOT NULL DEFAULT 0  -- 0隐藏  1显示
)ENGINE=MYISAM DEFAULT CHARSET=utf8;

-- 商品表
CREATE TABLE IF NOT EXISTS `s48_goods`(
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(255) NOT NULL,
  `cid` int(10) unsigned NOT NULL,
  `image` varchar(255) NOT NULL,
  `pay` decimal(10,2) NOT NULL,
  `stock` int(10) unsigned NOT NULL,
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `hot` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `new` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `best` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `time` int(10) unsigned NOT NULL,
  `decribe` text,
  `out` int(10) unsigned NOT NULL DEFAULT 0
)ENGINE=MYISAM DEFAULT CHARSET=utf8;

-- 商品图片表
CREATE TABLE IF NOT EXISTS `s48_image`(
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `gid` INT UNSIGNED NOT NULL,
  `face` TINYINT UNSIGNED NOT NULL DEFAULT 0
)ENGINE=MYISAM DEFAULT CHARSET=utf8;

-- 订单表
CREATE TABLE IF NOT EXISTS `s48_order`(
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `num` VARCHAR(255) NOT NULL UNIQUE KEY, 
  `name` VARCHAR(255) NOT NULL,
  `add` VARCHAR(255) NOT NULL,
  `tel` VARCHAR(255) NOT NULL,
  `post` INT UNSIGNED NOT NULL DEFAULT 0,
  `uid` INT UNSIGNED NOT NULL,
  `pay` DECIMAL(10,2) NOT NULL,
  `mess` VARCHAR(255) NOT NULL DEFAULT 0,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1
)ENGINE=MYISAM DEFAULT CHARSET=utf8;

-- 订单详情表
CREATE TABLE IF NOT EXISTS `s48_order_goods`(
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `gid` INT UNSIGNED NOT NULL,
  `pay` DECIMAL(10,0) NOT NULL,
  `num` INT UNSIGNED NOT NULL,
  `oid` INT UNSIGNED NOT NULL
)ENGINE=MYISAM DEFAULT CHARSET=utf8;

-- 商品评论表
CREATE TABLE IF NOT EXISTS `s48_discuss`(
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `uid` INT UNSIGNED NOT NULL DEFAULT 0,
  `gid` INT UNSIGNED NOT NULL DEFAULT 0,
  `time` INT UNSIGNED NOT NULL DEFAULT 0,
  `discuss` TEXT,
  `lock` TINYINT NOT NULL DEFAULT 0
)ENGINE=MYISAM DEFAULT CHARSET=utf8;

-- 创建删除订单触发器
CREATE TRIGGER DEL_ORDER_GOODS
AFTER
DELETE
ON s48_order
FOR EACH ROW
BEGIN
DELETE FROM s48_order_goods WHERE oid=OLD.ID;
END$